#!/usr/bin/env python
# encoding: utf-8

import curses

#curses.initscr()                        # Initialize the library. 
#                                        # Return a WindowObject 
#                                        # which represents the whole screen.
#
#win = curses.newwin(20, 60, 0, 0)       # Return a new window, whose 
#                                        # left-upper corner is at 
#                                        # (begin_y, begin_x), and 
#                                        # whose height/width is nlines/ncols.
#
#win.keypad(1)                           # If yes is 1, escape sequences 
#                                        # generated by some keys 
#                                        # (keypad, function keys) 
#                                        # will be interpreted by curses. 
#
#curses.noecho()                         # Echoing of character is turned off.
#
#curses.curs_set(0)                      # set cursor state 0 - invisible, 
#                                        # 1 - visible, 2 - very visible
#
#win.border()                            # Draws a border around windows. 
#                                        # Optional positional parameters 
#                                        # define which character to use
#                                        # for window border.
#
#win.nodelay(0)                          # Makes win.getch()
#                                        #        0 - blocking
#                                        #        1 - non-blocking
#
#key = win.getch()                       # get a character
#
#curses.endwin()                         # de-initialize library and return 
#                                        # window to normal mode


RIGHT = (0, 1)
LEFT = (0, -1)
UP = (-1, 0)
DOWN = (1, 0)

class Board(object):

    def __init__(self, ylen=30, xlen=80, ybegin=0, ybegin=0):
        self._ylen = ylen
        self._xlen = xlen
        self._ybegin = ybegin
        self._ybegin = ybegin
        self._score = 0
        self._is_over = False

    def __enter__(self):
        curses.initscr()
        win = curses.newwin(20, 60, 0, 0)
        win.keypad(1)
        curses.noecho()
        curses.curs_set(0)
        win.border()
        win.nodelay(0)

    def __exit__(self, *args):
        key = win.getch()
        curses.endwin()
        
    def show_score(self):
        pass

    def is_over(self):
        pass

    def place_apple(self):
        pass

class Snake(object):

    def __init__(self, cordinates=None):
        if cordinates == None:
            self._cordinates = [(10, 3), (10, 4), (10, 5), (10, 6), (10, 7)]
        else:
            self._cordinates = cordinates

        self._direction = RIGHT

    def move(self):
        pass

if __name__ == '__main__':
    main()
