#!/usr/bin/env python
# encoding: utf-8


import curses

curses.initscr()                        # Initialize the library. 
                                        # Return a WindowObject 
                                        # which represents the whole screen.

win = curses.newwin(20, 60, 0, 0)       # Return a new window, whose 
                                        # left-upper corner is at 
                                        # (begin_y, begin_x), and 
                                        # whose height/width is nlines/ncols.

win.keypad(1)                           # If yes is 1, escape sequences 
                                        # generated by some keys 
                                        # (keypad, function keys) 
                                        # will be interpreted by curses. 

curses.noecho()                         # Echoing of character is turned off.

curses.curs_set(0)                      # set cursor state 0 - invisible, 
                                        # 1 - visible, 2 - very visible

win.border()                            # Draws a border around windows. 
                                        # Optional positional parameters 
                                        # define which character to use
                                        # for window border.

win.nodelay(0)                          # Makes win.getch()
                                        #        0 - blocking
                                        #        1 - non-blocking

key = win.getch()                       # get a character

curses.endwin()                         # de-initialize library and return 
                                        # window to normal mode


class Board(object):

    """Docstring for Board. """

    def __init__(self, ylen=30, xlen=80, ybegin=0, ybegin=0):
        self._ylen = ylen
        self._xlen = xlen
        self._ybegin = ybegin
        self._ybegin = ybegin
        
    def show_score(self):
        pass

    def is_over(self):
        pass


