# SNAKES GAME
# Use ARROW KEYS to play, SPACE BAR for pausing/resuming and Esc Key for exiting

import curses

#curses.initscr()                        # Initialize the library. 
#                                        # Return a WindowObject 
#                                        # which represents the whole screen.
#
#win = curses.newwin(20, 60, 0, 0)       # Return a new window, whose 
#       # height, width, top, left       # left-upper corner is at 
#                                        # (begin_y, begin_x), and 
#                                        # whose height/width is nlines/ncols.
#
#win.keypad(1)                           # If yes is 1, escape sequences 
#                                        # generated by some keys 
#                                        # (keypad, function keys) 
#                                        # will be interpreted by curses. 
#
#curses.noecho()                         # Echoing of character is turned off.
#
#curses.curs_set(0)                      # set cursor state 0 - invisible, 
#                                        # 1 - visible, 2 - very visible
#
#win.border()                            # Draws a border around windows. 
#                                        # Optional positional parameters 
#                                        # define which character to use
#                                        # for window border.
#
#win.nodelay(0)                          # Makes win.getch()
#                                        #        0 - blocking
#                                        #        1 - non-blocking
#
#key = win.getch()                       # get a character
#
#curses.endwin()                         # de-initialize library and return 
#                                        # window to normal mode

class Board(object):
    def __init__(object, beginx=0, beginy=0, width=80, height=30):
        self._beginx = beginx
        self._beginy = beginy
        self._width = width
        self._height = height

    def __enter__(self):
        curses.initscr()                        
        win = curses.newwin(self._height, self._width, self._height, self._width)       
               # height, width, top, left       
        win.keypad(1)                           
        curses.noecho()                         
        curses.curs_set(0)                      
        win.border()                            
        win.nodelay(0)                          
        key = win.getch()                       

    def __exit__(self, *args):
        curses.endwin()

if __name__ == '__main__':
    with Board():
        pass

