#!/usr/bin/env python
# encoding: utf-8

import curses

#curses.initscr()                        # Initialize the library. 
#                                        # Return a WindowObject 
#                                        # which represents the whole screen.
#
#win = curses.newwin(20, 60, 0, 0)       # Return a new window, whose 
#       # height, width, top, left       # left-upper corner is at 
#                                        # (begin_y, begin_x), and 
#                                        # whose height/width is nlines/ncols.
#
#win.keypad(1)                           # If yes is 1, escape sequences 
#                                        # generated by some keys 
#                                        # (keypad, function keys) 
#                                        # will be interpreted by curses. 
#
#curses.noecho()                         # Echoing of character is turned off.
#
#curses.curs_set(0)                      # set cursor state 0 - invisible, 
#                                        # 1 - visible, 2 - very visible
#
#win.border()                            # Draws a border around windows. 
#                                        # Optional positional parameters 
#                                        # define which character to use
#                                        # for window border.
#
#win.nodelay(0)                          # Makes win.getch()
#                                        #        0 - blocking
#                                        #        1 - non-blocking
#
#key = win.getch()                       # get a character
#
#curses.endwin()                         # de-initialize library and return 
#                                        # window to normal mode

UP = (-1, 0)
DOWN = (1, 0)
LEFT = (0, -1)
RIGHT = (0, 1)

class Board(object):
    def __init__(self, beginx=0, beginy=0, width=80, height=30):
        self._beginx = beginx
        self._beginy = beginy
        self._width = width
        self._height = height

    def __enter__(self):
        curses.initscr()                        
        win = curses.newwin(self._height, self._width, self._beginy, self._beginx)       
               # height, width, top, left       
        win.keypad(1)                           
        curses.noecho()                         
        curses.curs_set(0)                      
        win.border()                            
        win.nodelay(1)                          
        self._win = win
        return self

    def __exit__(self, *args):
        key = self._win.getch()                       
        curses.endwin()

    def draw_char(self, y, x, char):
        self._win.addch(y, x, char)

    def getch(self):
        return self._win.getch()

    def endgame(self):
        self._win.addstr(3, 3, "Game over!!")
        pass


class Snake(object):
    def __init__(self, board):
        self._cordinates = [(10,3), (10,4), (10,5)]
        self._cordinates
        self._direction = RIGHT
        self._board = board

    def move(self):
        head = list(self._cordinates[-1])
        head[0] += self._direction[0]
        head[1] += self._direction[1]
        self._cordinates.append(tuple(head))
        self._board.draw_char(head[0], head[1], '#')
        tail = self._cordinates.pop(0)
        self._board.draw_char(tail[0], tail[1], ' ')

    def draw(self):
        for c in self._cordinates:
            self._board.draw_char(c[0], c[1], '#')

    def change_direction(self, key):
        if key == curses.KEY_LEFT and not self._direction == RIGHT:
            self._direction = LEFT
        elif key == curses.KEY_RIGHT and not self._direction == LEFT:
            self._direction = RIGHT
        elif key == curses.KEY_UP and not self._direction == DOWN:
            self._direction = UP
        elif key == curses.KEY_DOWN and not self._direction == UP:
            self._direction = DOWN
        else:
            pass

if __name__ == '__main__':
    with Board() as b:
        snake = Snake(b)
        snake.draw()
        while True:
            snake.move()
            user_key = b.getch()
            snake.change_direction(user_key)
            import time; time.sleep(0.1)
